# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 1443, host: 1443
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  config.vm.network "public_network", ip: "192.168.0.101"

  # config.vm.synced_folder "./vm_share", "/mnt/vm_share"
  config.vm.provision :file, source: '../yggdrasil.AppDir', destination: "$HOME/yggdrasil.AppDir"
  # config.vm.provision :file, source: '../yggdrasil.AppDir/yggdrasil.conf', destination: "$HOME/yggdrasil.conf"
  config.vm.provision :file, source: '../build.sh', destination: "$HOME/build.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--vram", "128"]

    vb.cpus = 2
    vb.memory = "1024"

    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  config.vm.provision "shell",inline: <<-SHELL
    sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
    sudo systemctl restart sshd

    chmod +x /home/vagrant/build.sh
    chmod +rwx -R /home/vagrant/yggdrasil.AppDir

    apt-get update

    #Debug
    apt-get install -y htop vim net-tools curl git mc

    # Yggdrasil from source
    wget -q https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz
    tar xf go1.15.6.linux-amd64.tar.gz
    chown -R root:root ./go
    cp -r go /usr/bin
    cp -r go /usr/local
    echo "PATH=$PATH:/usr/bin/go/bin:$GOPATH/bin" >> /home/vagrant/.profile
    echo "PATH=$PATH:/usr/bin/go/bin:$GOPATH/bin" >> /root/.profile
    export PATH=$PATH:/usr/bin/go/bin:$GOPATH/bin
    echo "PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> /home/vagrant/.profile
    echo "PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> /root/.profile
    export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

    git clone -b master https://github.com/yggdrasil-network/yggdrasil-go.git #/home/vagrant/yggdrasil-go
    cd yggdrasil-go
    source /root/.profile
    ./build
    cp {yggdrasil,yggdrasilctl} /home/vagrant/yggdrasil.AppDir/usr/bin/
    chown -R vagrant:vagrant /home/vagrant/yggdrasil.AppDir

    # Yggdrasil from repo
    # sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
    # sudo apt-get install -y dirmngr
    # sudo gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
    # sudo gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
    # sudo echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
    # sudo apt-get update
    # sudo apt-get install -y yggdrasil
    # sudo systemctl enable yggdrasil
    # sudo systemctl start yggdrasil

    # Appimage packages
    apt-get install fuse
    wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /home/vagrant/appimagetool-x86_64.AppImage
    chmod +x /home/vagrant/appimagetool-x86_64.AppImage

    bash /home/vagrant/build.sh

    sudo chown vagrant:vagrant -R /home/vagrant/yggdrasil.AppDir

    # DE
    # # apt-get install -y xfce4-goodies
    # apt-get install -y task-xfce-desktop
    # systemctl set-default graphical.target

    sudo systemctl restart sshd
  SHELL
end
