# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddContactDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddContact(object):
    def setupUi(self, DialogAddContact):
        DialogAddContact.setObjectName("DialogAddContact")
        DialogAddContact.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogAddContact.resize(320, 240)
        DialogAddContact.setMinimumSize(QtCore.QSize(320, 240))
        DialogAddContact.setMaximumSize(QtCore.QSize(320, 240))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAddContact)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineNickname = QtWidgets.QLineEdit(DialogAddContact)
        self.lineNickname.setObjectName("lineNickname")
        self.verticalLayout.addWidget(self.lineNickname)
        self.lineNewContactUuid = QtWidgets.QLineEdit(DialogAddContact)
        self.lineNewContactUuid.setObjectName("lineNewContactUuid")
        self.verticalLayout.addWidget(self.lineNewContactUuid)
        self.lineNewContactIp = QtWidgets.QLineEdit(DialogAddContact)
        self.lineNewContactIp.setObjectName("lineNewContactIp")
        self.verticalLayout.addWidget(self.lineNewContactIp)
        self.lineNewContactPort = QtWidgets.QLineEdit(DialogAddContact)
        self.lineNewContactPort.setObjectName("lineNewContactPort")
        self.verticalLayout.addWidget(self.lineNewContactPort)
        self.labelError = QtWidgets.QLabel(DialogAddContact)
        self.labelError.setEnabled(True)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.verticalLayout.addWidget(self.labelError)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(DialogAddContact)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonAdd = QtWidgets.QPushButton(DialogAddContact)
        self.pushButtonAdd.setAutoDefault(False)
        self.pushButtonAdd.setDefault(True)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogAddContact)
        QtCore.QMetaObject.connectSlotsByName(DialogAddContact)

    def retranslateUi(self, DialogAddContact):
        _translate = QtCore.QCoreApplication.translate
        DialogAddContact.setWindowTitle(_translate("DialogAddContact", "Add Contact"))
        self.lineNickname.setPlaceholderText(_translate("DialogAddContact", "Nickname"))
        self.lineNewContactUuid.setPlaceholderText(_translate("DialogAddContact", "UUID"))
        self.lineNewContactIp.setPlaceholderText(_translate("DialogAddContact", "IP Address"))
        self.lineNewContactPort.setPlaceholderText(_translate("DialogAddContact", "Port"))
        self.pushButtonCancel.setText(_translate("DialogAddContact", "Cancel"))
        self.pushButtonAdd.setText(_translate("DialogAddContact", "Add"))
