# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNewProfile(object):
    def setupUi(self, DialogNewProfile):
        DialogNewProfile.setObjectName("DialogNewProfile")
        DialogNewProfile.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogNewProfile.resize(360, 120)
        DialogNewProfile.setMinimumSize(QtCore.QSize(320, 120))
        DialogNewProfile.setMaximumSize(QtCore.QSize(360, 140))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNewProfile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutIp = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIp.setObjectName("horizontalLayoutIp")
        self.labelIp = QtWidgets.QLabel(DialogNewProfile)
        self.labelIp.setObjectName("labelIp")
        self.horizontalLayoutIp.addWidget(self.labelIp)
        self.lineEditIp = QtWidgets.QLineEdit(DialogNewProfile)
        self.lineEditIp.setText("")
        self.lineEditIp.setPlaceholderText("")
        self.lineEditIp.setObjectName("lineEditIp")
        self.horizontalLayoutIp.addWidget(self.lineEditIp)
        self.verticalLayout.addLayout(self.horizontalLayoutIp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelError = QtWidgets.QLabel(DialogNewProfile)
        self.labelError.setObjectName("labelError")
        self.horizontalLayout.addWidget(self.labelError)
        self.pushButtonCreate = QtWidgets.QPushButton(DialogNewProfile)
        self.pushButtonCreate.setDefault(True)
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.horizontalLayout.addWidget(self.pushButtonCreate)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogNewProfile)
        self.pushButtonCancel.setDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogNewProfile)
        QtCore.QMetaObject.connectSlotsByName(DialogNewProfile)

    def retranslateUi(self, DialogNewProfile):
        _translate = QtCore.QCoreApplication.translate
        DialogNewProfile.setWindowTitle(_translate("DialogNewProfile", "New Profile"))
        self.labelIp.setText(_translate("DialogNewProfile", "IP:"))
        self.labelError.setText(_translate("DialogNewProfile", "Error (!)"))
        self.pushButtonCreate.setText(_translate("DialogNewProfile", "Create"))
        self.pushButtonCancel.setText(_translate("DialogNewProfile", "Cancel"))
