# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNewUser(object):
    def setupUi(self, DialogNewUser):
        DialogNewUser.setObjectName("DialogNewUser")
        DialogNewUser.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogNewUser.resize(360, 180)
        DialogNewUser.setMinimumSize(QtCore.QSize(320, 160))
        DialogNewUser.setMaximumSize(QtCore.QSize(360, 180))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNewUser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutIp = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIp.setObjectName("horizontalLayoutIp")
        self.labelIp = QtWidgets.QLabel(DialogNewUser)
        self.labelIp.setObjectName("labelIp")
        self.horizontalLayoutIp.addWidget(self.labelIp)
        self.lineEditIp = QtWidgets.QLineEdit(DialogNewUser)
        self.lineEditIp.setText("")
        self.lineEditIp.setPlaceholderText("")
        self.lineEditIp.setObjectName("lineEditIp")
        self.horizontalLayoutIp.addWidget(self.lineEditIp)
        self.verticalLayout.addLayout(self.horizontalLayoutIp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelError = QtWidgets.QLabel(DialogNewUser)
        self.labelError.setObjectName("labelError")
        self.horizontalLayout.addWidget(self.labelError)
        self.pushButtonCreate = QtWidgets.QPushButton(DialogNewUser)
        self.pushButtonCreate.setDefault(True)
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.horizontalLayout.addWidget(self.pushButtonCreate)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogNewUser)
        self.pushButtonCancel.setDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogNewUser)
        QtCore.QMetaObject.connectSlotsByName(DialogNewUser)

    def retranslateUi(self, DialogNewUser):
        _translate = QtCore.QCoreApplication.translate
        DialogNewUser.setWindowTitle(_translate("DialogNewUser", "New Account"))
        self.labelIp.setText(_translate("DialogNewUser", "IP:"))
        self.labelError.setText(_translate("DialogNewUser", "Error (!)"))
        self.pushButtonCreate.setText(_translate("DialogNewUser", "Create"))
        self.pushButtonCancel.setText(_translate("DialogNewUser", "Cancel"))
