#!/bin/bash
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"

get_sudo_password=`bash $HERE/get_sudo_password.sh`
sudo_password=`echo $get_sudo_password | sed "s|Password : ||g"`

test_pass=`echo $sudo_password | sudo -S -s $HERE/check_EUID.sh`

if (( test_pass == 0)) ; then
    echo $sudo_password | sudo -S -s -u root yggdrasil.AppDir/usr/bin/yggdrasil -genconf > /tmp/yggdrasil.conf
    echo $sudo_password | sudo -S -s -u root sed 's|Peers: \[\]|Peers: \[ \n tcp://46.151.26.194:60575 \n \]|g' -i /tmp/yggdrasil.conf
    echo $sudo_password | sudo -S -s -u root yggdrasil.AppDir/usr/bin/yggdrasil -useconffile /tmp/yggdrasil.conf
fi
